language: ruby
before_install:
  - sudo apt-get autoremove sqlite3
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-cache show sqlite3
  - sudo apt-get install sqlite3=3.7.15.1-1~travis1
  - sudo sqlite3 -version
  - gem update bundler
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
  - "2.1.9"
  - "2.2.5"
  - "2.3.1"
script: bundle exec rspec spec
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
